-- MySQL Script generated by MySQL Workbench
-- Fri May  5 10:47:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quan_ly_tien_do_hoc_tap
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quan_ly_tien_do_hoc_tap` ;

-- -----------------------------------------------------
-- Schema quan_ly_tien_do_hoc_tap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quan_ly_tien_do_hoc_tap` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `quan_ly_tien_do_hoc_tap` ;

-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`chung_chi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`chung_chi` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`chung_chi` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten_chung_chi` NVARCHAR(255) NOT NULL,
  `ghi_chu` TEXT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`khoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`khoa` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`khoa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ma_khoa` VARCHAR(255) NOT NULL,
  `ten` NVARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ma_khoa_UNIQUE` (`ma_khoa` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`nganh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`nganh` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`nganh` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ma_nganh` VARCHAR(255) NOT NULL,
  `ten` NVARCHAR(255) NOT NULL,
  `khoa_id` INT UNSIGNED NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_nganh_khoa1_idx` (`khoa_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ma_nganh_UNIQUE` (`ma_nganh` ASC) VISIBLE,
  CONSTRAINT `fk_nganh_khoa1`
    FOREIGN KEY (`khoa_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`khoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`chu_ky`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`chu_ky` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`chu_ky` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nam_bat_dau` YEAR NOT NULL,
  `nam_ket_thuc` YEAR NULL,
  `ten` NVARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`chuong_trinh_dao_tao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`chuong_trinh_dao_tao` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`chuong_trinh_dao_tao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` NVARCHAR(255) NOT NULL,
  `tong_tin_chi` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'tổng tín chỉ tối thiểu',
  `thoi_gian_dao_tao` FLOAT UNSIGNED NOT NULL,
  `trinh_do_dao_tao` NVARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `nganh_id` INT UNSIGNED NOT NULL,
  `chu_ky_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chuong_trinh_dao_tao_nganh1_idx` (`nganh_id` ASC) VISIBLE,
  INDEX `fk_chuong_trinh_dao_tao_chu_ky1_idx` (`chu_ky_id` ASC) VISIBLE,
  CONSTRAINT `fk_chuong_trinh_dao_tao_nganh1`
    FOREIGN KEY (`nganh_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`nganh` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chuong_trinh_dao_tao_chu_ky1`
    FOREIGN KEY (`chu_ky_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`chu_ky` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`hoc_phan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id là mã học phần luôn',
  `ten` NVARCHAR(255) NOT NULL,
  `so_tin_chi` TINYINT UNSIGNED NOT NULL,
  `phan_tram_giua_ki` TINYINT UNSIGNED NOT NULL,
  `phan_tram_cuoi_ki` TINYINT UNSIGNED NOT NULL,
  `co_tinh_tich_luy` TINYINT NULL DEFAULT 1,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `hoc_phan_tuong_duong_id` INT UNSIGNED NULL,
  `ma_hoc_phan` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hoc_phan_hoc_phan1_idx` (`hoc_phan_tuong_duong_id` ASC) VISIBLE,
  UNIQUE INDEX `ma_hoc_phan_UNIQUE` (`ma_hoc_phan` ASC) VISIBLE,
  CONSTRAINT `fk_hoc_phan_hoc_phan1`
    FOREIGN KEY (`hoc_phan_tuong_duong_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`quyen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`quyen` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`quyen` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` NVARCHAR(255) NOT NULL,
  `ten_slug` VARCHAR(255) NOT NULL,
  `ghi_chu` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ten_slug_UNIQUE` (`ten_slug` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`tai_khoan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`tai_khoan` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`tai_khoan` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` NVARCHAR(255) NOT NULL,
  `ten_dang_nhap` VARCHAR(255) NOT NULL,
  `mat_khau` VARCHAR(100) CHARACTER SET 'big5' NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `quyen_id` SMALLINT UNSIGNED NULL,
  `email` VARCHAR(255) NULL,
  `sdt` VARCHAR(255) NULL,
  `ngay_sinh` DATETIME NULL,
  `gioi_tinh` TINYINT NOT NULL DEFAULT 0,
  `khoa_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_UNIQUE` (`ten_dang_nhap` ASC) VISIBLE,
  INDEX `fk_tai_khoan_quyen1_idx` (`quyen_id` ASC) VISIBLE,
  INDEX `fk_tai_khoan_khoa1_idx` (`khoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_tai_khoan_quyen1`
    FOREIGN KEY (`quyen_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`quyen` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tai_khoan_khoa1`
    FOREIGN KEY (`khoa_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`khoa` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`bien_che`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`bien_che` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`bien_che` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` NVARCHAR(255) NOT NULL,
  `ngay_bat_dau` DATETIME NOT NULL,
  `ngay_ket_thuc` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ky_he` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`ket_qua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`ket_qua` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`ket_qua` (
  `hoc_phan_id` INT UNSIGNED NOT NULL,
  `sinh_vien_id` BIGINT UNSIGNED NOT NULL,
  `diem_qua_trinh` FLOAT(4,2) NULL DEFAULT NULL,
  `diem_cuoi_ky` FLOAT(4,2) NULL DEFAULT NULL,
  `diem_tong_ket` FLOAT(4,2) NULL DEFAULT NULL,
  `diem_he_4` FLOAT(4,2) NULL DEFAULT NULL,
  `loai_he_4` VARCHAR(3) NULL DEFAULT NULL,
  `qua_mon` TINYINT NULL DEFAULT 0,
  `bien_che_id` SMALLINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INDEX `fk_ket_qua_nguoi_dung1_idx` (`sinh_vien_id` ASC) VISIBLE,
  INDEX `fk_ket_qua_bien_che1_idx` (`bien_che_id` ASC) VISIBLE,
  UNIQUE INDEX `hoc_phan_id_UNIQUE` (`hoc_phan_id` ASC, `sinh_vien_id` ASC) INVISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ket_qua_hoc_phan1`
    FOREIGN KEY (`hoc_phan_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`hoc_phan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ket_qua_nguoi_dung1`
    FOREIGN KEY (`sinh_vien_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tai_khoan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ket_qua_bien_che1`
    FOREIGN KEY (`bien_che_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`bien_che` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`nhom_hoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`nhom_hoc` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`nhom_hoc` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `so_luong_sinh_vien` SMALLINT UNSIGNED NULL DEFAULT 0,
  `stt_nhom` VARCHAR(4) NOT NULL,
  `nhom_thuc_hanh` VARCHAR(4) NOT NULL,
  `hoc_phan_id` INT UNSIGNED NOT NULL,
  `giang_vien_id` BIGINT UNSIGNED NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_nhom_hoc_hoc_phan1_idx` (`hoc_phan_id` ASC) VISIBLE,
  INDEX `fk_nhom_hoc_nguoi_dung1_idx` (`giang_vien_id` ASC) INVISIBLE,
  UNIQUE INDEX `stt_nhom_UNIQUE` (`stt_nhom` ASC, `nhom_thuc_hanh` ASC, `hoc_phan_id` ASC) INVISIBLE,
  CONSTRAINT `fk_nhom_hoc_hoc_phan1`
    FOREIGN KEY (`hoc_phan_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nhom_hoc_nguoi_dung1`
    FOREIGN KEY (`giang_vien_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tai_khoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`bai_dang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`bai_dang` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`bai_dang` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tieu_de` NVARCHAR(255) NOT NULL,
  `noi_dung` TEXT NOT NULL,
  `loai_noi_dung` TINYINT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `nhom_hoc_id` INT UNSIGNED NULL,
  `nguoi_dung_id` BIGINT UNSIGNED NOT NULL,
  `ngay_bat_dau` TIMESTAMP NULL,
  `ngay_ket_thuc` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_noi_dung_nhom_hoc_nhom_hoc1_idx` (`nhom_hoc_id` ASC) VISIBLE,
  INDEX `fk_bai_dang_nguoi_dung1_idx` (`nguoi_dung_id` ASC) VISIBLE,
  CONSTRAINT `fk_noi_dung_nhom_hoc_nhom_hoc1`
    FOREIGN KEY (`nhom_hoc_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`nhom_hoc` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bai_dang_nguoi_dung1`
    FOREIGN KEY (`nguoi_dung_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tai_khoan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`tham_gia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`tham_gia` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`tham_gia` (
  `nhom_hoc_id` INT UNSIGNED NOT NULL,
  `sinh_vien_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`nhom_hoc_id`, `sinh_vien_id`),
  INDEX `fk_tham_gia_nhom_hoc1_idx` (`nhom_hoc_id` ASC) INVISIBLE,
  INDEX `fk_tham_gia_nguoi_dung1_idx` (`sinh_vien_id` ASC) VISIBLE,
  CONSTRAINT `fk_tham_gia_nhom_hoc1`
    FOREIGN KEY (`nhom_hoc_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`nhom_hoc` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tham_gia_nguoi_dung1`
    FOREIGN KEY (`sinh_vien_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tai_khoan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`chuan_dau_ra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`chuan_dau_ra` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`chuan_dau_ra` (
  `chung_chi_id` INT UNSIGNED NOT NULL,
  `chuong_trinh_dao_tao_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`chung_chi_id`, `chuong_trinh_dao_tao_id`),
  INDEX `fk_chuan_dau_ra_chuong_trinh_dao_tao1_idx` (`chuong_trinh_dao_tao_id` ASC) VISIBLE,
  CONSTRAINT `fk_chuan_dau_ra_chung_chi1`
    FOREIGN KEY (`chung_chi_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`chung_chi` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chuan_dau_ra_chuong_trinh_dao_tao1`
    FOREIGN KEY (`chuong_trinh_dao_tao_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`chuong_trinh_dao_tao` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`moc_thoi_gian_tot_nghiep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`moc_thoi_gian_tot_nghiep` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`moc_thoi_gian_tot_nghiep` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nam` YEAR NOT NULL DEFAULT 0,
  `dot` TINYINT NOT NULL DEFAULT 0,
  `ten` NVARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nam_UNIQUE` (`nam` ASC, `dot` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`lop_hoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`lop_hoc` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`lop_hoc` (
  `co_van_hoc_tap_id` BIGINT UNSIGNED NULL,
  `ten_lop` NVARCHAR(255) NOT NULL,
  `ma_lop` VARCHAR(255) NOT NULL,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `chuong_trinh_dao_tao_id` INT UNSIGNED NULL,
  `thoi_gian_vao_hoc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `thoi_gian_ket_thuc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `so_luong_sinh_vien` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_lop_hoc_nguoi_dung2_idx` (`co_van_hoc_tap_id` ASC) VISIBLE,
  UNIQUE INDEX `nien_khoa_id_UNIQUE` (`co_van_hoc_tap_id` ASC) VISIBLE,
  INDEX `fk_lop_hoc_chuong_trinh_dao_tao1_idx` (`chuong_trinh_dao_tao_id` ASC) VISIBLE,
  UNIQUE INDEX `ma_lop_UNIQUE` (`ma_lop` ASC) VISIBLE,
  CONSTRAINT `fk_lop_hoc_nguoi_dung2`
    FOREIGN KEY (`co_van_hoc_tap_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tai_khoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lop_hoc_chuong_trinh_dao_tao1`
    FOREIGN KEY (`chuong_trinh_dao_tao_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`chuong_trinh_dao_tao` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`loai_kien_thuc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`loai_kien_thuc` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`loai_kien_thuc` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` TINYTEXT NOT NULL COMMENT 'Khối kiến thức giáo dục đại cương\nnó ở mục 1\n',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `dai_cuong` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`khoi_kien_thuc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`khoi_kien_thuc` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`khoi_kien_thuc` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` NVARCHAR(255) NOT NULL COMMENT 'số hiệu',
  `loai_kien_thuc_id` SMALLINT UNSIGNED NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tong_tin_chi_ktt_tu_chon` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `tong_tin_chi_ktt_bat_buoc` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `tong_tin_chi` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `chuong_trinh_dao_tao_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_khoi_kien_thuc_loai_kien_thuc1_idx` (`loai_kien_thuc_id` ASC) VISIBLE,
  INDEX `fk_khoi_kien_thuc_chuong_trinh_dao_tao1_idx` (`chuong_trinh_dao_tao_id` ASC) VISIBLE,
  UNIQUE INDEX `loai_kien_thuc_id_UNIQUE` (`loai_kien_thuc_id` ASC, `chuong_trinh_dao_tao_id` ASC) VISIBLE,
  CONSTRAINT `fk_khoi_kien_thuc_loai_kien_thuc1`
    FOREIGN KEY (`loai_kien_thuc_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`loai_kien_thuc` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_khoi_kien_thuc_chuong_trinh_dao_tao1`
    FOREIGN KEY (`chuong_trinh_dao_tao_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`chuong_trinh_dao_tao` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `so_lan_canh_cao` TINYINT NULL DEFAULT 0,
  `da_tot_nghiep` TINYINT NULL DEFAULT 0,
  `moc_thoi_gian_id` INT UNSIGNED NULL,
  `buoc_thoi_hoc` TINYINT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `sinh_vien_id` BIGINT UNSIGNED NOT NULL,
  `ly_do_buoc_thoi_hoc` TEXT NULL,
  `lop_hoc_id` INT UNSIGNED NULL,
  `khoi_kien_thuc_id` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tinh_trang_sinh_vien_moc_thoi_gian1_idx` (`moc_thoi_gian_id` ASC) VISIBLE,
  INDEX `fk_tinh_trang_sinh_vien_tai_khoan1_idx` (`sinh_vien_id` ASC) INVISIBLE,
  UNIQUE INDEX `sinh_vien_id_UNIQUE` (`sinh_vien_id` ASC) VISIBLE,
  INDEX `fk_tinh_trang_sinh_vien_lop_hoc1_idx` (`lop_hoc_id` ASC) VISIBLE,
  INDEX `fk_tinh_trang_sinh_vien_khoi_kien_thuc1_idx` (`khoi_kien_thuc_id` ASC) VISIBLE,
  CONSTRAINT `fk_tinh_trang_sinh_vien_moc_thoi_gian1`
    FOREIGN KEY (`moc_thoi_gian_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`moc_thoi_gian_tot_nghiep` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tinh_trang_sinh_vien_tai_khoan1`
    FOREIGN KEY (`sinh_vien_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tai_khoan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tinh_trang_sinh_vien_lop_hoc1`
    FOREIGN KEY (`lop_hoc_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`lop_hoc` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tinh_trang_sinh_vien_khoi_kien_thuc1`
    FOREIGN KEY (`khoi_kien_thuc_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`khoi_kien_thuc` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`sinh_vien_chung_chi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`sinh_vien_chung_chi` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`sinh_vien_chung_chi` (
  `chung_chi_id` INT UNSIGNED NOT NULL,
  `tinh_trang_sinh_vien_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`chung_chi_id`, `tinh_trang_sinh_vien_id`),
  INDEX `fk_sinh_vien_co_chung_chi_chung_chi1_idx` (`chung_chi_id` ASC) VISIBLE,
  INDEX `fk_sinh_vien_chung_chi_tinh_trang_sinh_vien1_idx` (`tinh_trang_sinh_vien_id` ASC) VISIBLE,
  CONSTRAINT `fk_sinh_vien_co_chung_chi_chung_chi1`
    FOREIGN KEY (`chung_chi_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`chung_chi` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sinh_vien_chung_chi_tinh_trang_sinh_vien1`
    FOREIGN KEY (`tinh_trang_sinh_vien_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`file_bai_dang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`file_bai_dang` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`file_bai_dang` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(255) NOT NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `bai_dang_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_file_bai_dang_bai_dang1_idx` (`bai_dang_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_bai_dang_bai_dang1`
    FOREIGN KEY (`bai_dang_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`bai_dang` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`binh_luan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`binh_luan` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`binh_luan` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `noi_dung` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `bai_dang_id` BIGINT UNSIGNED NOT NULL,
  `nguoi_dung_id` BIGINT UNSIGNED NOT NULL,
  `binh_luan_id` BIGINT UNSIGNED NULL,
  `path_enumeration` VARCHAR(250) NULL COMMENT '1/\n1/2/\n1/2/3\n1/4/',
  PRIMARY KEY (`id`),
  INDEX `fk_file_bai_dang_bai_dang1_idx` (`bai_dang_id` ASC) VISIBLE,
  INDEX `fk_binh_luan_nguoi_dung1_idx` (`nguoi_dung_id` ASC) VISIBLE,
  INDEX `fk_binh_luan_binh_luan1_idx` (`binh_luan_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_bai_dang_bai_dang10`
    FOREIGN KEY (`bai_dang_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`bai_dang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binh_luan_nguoi_dung1`
    FOREIGN KEY (`nguoi_dung_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tai_khoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binh_luan_binh_luan1`
    FOREIGN KEY (`binh_luan_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`binh_luan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`file_binh_luan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`file_binh_luan` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`file_binh_luan` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(255) NOT NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `binh_luan_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_file_binh_luan_binh_luan1_idx` (`binh_luan_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_binh_luan_binh_luan1`
    FOREIGN KEY (`binh_luan_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`binh_luan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`chuc_nang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`chuc_nang` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`chuc_nang` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` NVARCHAR(255) NOT NULL,
  `icon` VARCHAR(255) NOT NULL DEFAULT '',
  `href` VARCHAR(255) NOT NULL DEFAULT '',
  `ghi_chu` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`dieu_kien_tien_quyet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`dieu_kien_tien_quyet` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`dieu_kien_tien_quyet` (
  `hoc_phan_id` INT UNSIGNED NOT NULL,
  `hoc_phan_truoc_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`hoc_phan_id`, `hoc_phan_truoc_id`),
  INDEX `fk_dieu_kien_tien_quyet_hoc_phan2_idx` (`hoc_phan_truoc_id` ASC) VISIBLE,
  CONSTRAINT `fk_dieu_kien_tien_quyet_hoc_phan1`
    FOREIGN KEY (`hoc_phan_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dieu_kien_tien_quyet_hoc_phan2`
    FOREIGN KEY (`hoc_phan_truoc_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`chuc_nang_quyen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`chuc_nang_quyen` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`chuc_nang_quyen` (
  `chuc_nang_id` SMALLINT UNSIGNED NOT NULL,
  `quyen_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`chuc_nang_id`, `quyen_id`),
  INDEX `fk_chuc_nang_quyen_quyen1_idx` (`quyen_id` ASC) VISIBLE,
  CONSTRAINT `fk_chuc_nang_quyen_chuc_nang1`
    FOREIGN KEY (`chuc_nang_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`chuc_nang` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chuc_nang_quyen_quyen1`
    FOREIGN KEY (`quyen_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`quyen` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`bai_tap_sinh_vien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`bai_tap_sinh_vien` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`bai_tap_sinh_vien` (
  `bai_tap_id` BIGINT UNSIGNED NOT NULL,
  `sinh_vien_id` BIGINT UNSIGNED NOT NULL,
  `diem` SMALLINT UNSIGNED NULL DEFAULT 0,
  `link_file` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`bai_tap_id`, `sinh_vien_id`),
  INDEX `fk_bai_tap_sinh_vien_tai_khoan1_idx` (`sinh_vien_id` ASC) VISIBLE,
  CONSTRAINT `fk_bai_tap_bai_dang1`
    FOREIGN KEY (`bai_tap_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`bai_dang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bai_tap_sinh_vien_tai_khoan1`
    FOREIGN KEY (`sinh_vien_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`tai_khoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_bat_buoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_bat_buoc` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_bat_buoc` (
  `hoc_phan_id` INT UNSIGNED NOT NULL,
  `hoc_ky_goi_y` SMALLINT NOT NULL,
  `khoi_kien_thuc_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`hoc_phan_id`, `hoc_ky_goi_y`, `khoi_kien_thuc_id`),
  INDEX `fk_hoc_phan_has_kkt_bat_buoc_hoc_phan1_idx` (`hoc_phan_id` ASC) VISIBLE,
  INDEX `fk_hoc_phan_kkt_bat_buoc_khoi_kien_thuc1_idx` (`khoi_kien_thuc_id` ASC) VISIBLE,
  CONSTRAINT `fk_hoc_phan_has_kkt_bat_buoc_hoc_phan1`
    FOREIGN KEY (`hoc_phan_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`hoc_phan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hoc_phan_kkt_bat_buoc_khoi_kien_thuc1`
    FOREIGN KEY (`khoi_kien_thuc_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`khoi_kien_thuc` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_tu_chon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_tu_chon` ;

CREATE TABLE IF NOT EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_tu_chon` (
  `hoc_phan_id` INT UNSIGNED NOT NULL,
  `hoc_ky_goi_y` SMALLINT NOT NULL,
  `khoi_kien_thuc_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`hoc_phan_id`, `hoc_ky_goi_y`, `khoi_kien_thuc_id`),
  INDEX `fk_hoc_phan_has_kkt_tu_chon_hoc_phan1_idx` (`hoc_phan_id` ASC) VISIBLE,
  INDEX `fk_hoc_phan_kkt_tu_chon_khoi_kien_thuc1_idx` (`khoi_kien_thuc_id` ASC) VISIBLE,
  CONSTRAINT `fk_hoc_phan_has_kkt_tu_chon_hoc_phan1`
    FOREIGN KEY (`hoc_phan_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`hoc_phan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hoc_phan_kkt_tu_chon_khoi_kien_thuc1`
    FOREIGN KEY (`khoi_kien_thuc_id`)
    REFERENCES `quan_ly_tien_do_hoc_tap`.`khoi_kien_thuc` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `quan_ly_tien_do_hoc_tap`;

DELIMITER $$

USE `quan_ly_tien_do_hoc_tap`$$
DROP TRIGGER IF EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan_AFTER_UPDATE` $$
USE `quan_ly_tien_do_hoc_tap`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quan_ly_tien_do_hoc_tap`.`hoc_phan_AFTER_UPDATE` AFTER UPDATE ON `hoc_phan` FOR EACH ROW
BEGIN
/*Loop xem có tồn tại liên kết nào giữa học phần với khối kiến thức hay không*/
/*Loop xem có tồn tại liên kết nào giữa học phần với khối kiến thức hay không*/
    IF(OLD.so_tin_chi != NEW.so_tin_chi)
    THEN
    UPDATE khoi_kien_thuc 	
    SET khoi_kien_thuc.tong_tin_chi_ktt_bat_buoc = khoi_kien_thuc.tong_tin_chi_ktt_bat_buoc + NEW.so_tin_chi - OLD.so_tin_chi
    WHERE khoi_kien_thuc.id IN 
    ( 
        SELECT hoc_phan_kkt_bat_buoc.khoi_kien_thuc_id 
        FROM hoc_phan_kkt_bat_buoc
        WHERE hoc_phan_kkt_bat_buoc.hoc_phan_id = NEW.id
	);
    END IF;


END$$


USE `quan_ly_tien_do_hoc_tap`$$
DROP TRIGGER IF EXISTS `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien_AFTER_INSERT` $$
USE `quan_ly_tien_do_hoc_tap`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien_AFTER_INSERT` AFTER INSERT ON `tinh_trang_sinh_vien` FOR EACH ROW
BEGIN
  IF (NEW.lop_hoc_id is not NULL  )
  THEN
	UPDATE lop_hoc SET lop_hoc.so_luong_sinh_vien= lop_hoc.so_luong_sinh_vien+1 WHERE lop_hoc.id=New.lop_hoc_id;
  END IF;
END$$


USE `quan_ly_tien_do_hoc_tap`$$
DROP TRIGGER IF EXISTS `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien_AFTER_UPDATE` $$
USE `quan_ly_tien_do_hoc_tap`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien_AFTER_UPDATE` AFTER UPDATE ON `tinh_trang_sinh_vien` FOR EACH ROW
BEGIN
  IF (NEW.lop_hoc_id is not NULL AND OLD.lop_hoc_id !=  NEW.lop_hoc_id )
  THEN
	UPDATE lop_hoc SET lop_hoc.so_luong_sinh_vien= lop_hoc.so_luong_sinh_vien+1 WHERE lop_hoc.id=New.lop_hoc_id;
   	UPDATE lop_hoc SET lop_hoc.so_luong_sinh_vien= lop_hoc.so_luong_sinh_vien-1 WHERE lop_hoc.id=Old.lop_hoc_id;
  ELSEIF(NEW.lop_hoc_id IS NULL AND OLD.lop_hoc_id IS NOT NULL)
  THEN
  UPDATE lop_hoc SET lop_hoc.so_luong_sinh_vien= lop_hoc.so_luong_sinh_vien-1 WHERE lop_hoc.id=Old.lop_hoc_id;  
END IF;
END$$


USE `quan_ly_tien_do_hoc_tap`$$
DROP TRIGGER IF EXISTS `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien_AFTER_DELETE` $$
USE `quan_ly_tien_do_hoc_tap`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quan_ly_tien_do_hoc_tap`.`tinh_trang_sinh_vien_AFTER_DELETE` AFTER DELETE ON `tinh_trang_sinh_vien` FOR EACH ROW
BEGIN
  IF (old.lop_hoc_id is not NULL  )
  THEN
	UPDATE lop_hoc SET lop_hoc.so_luong_sinh_vien= lop_hoc.so_luong_sinh_vien-1 WHERE lop_hoc.id=Old.lop_hoc_id;
  END IF;
END$$


USE `quan_ly_tien_do_hoc_tap`$$
DROP TRIGGER IF EXISTS `quan_ly_tien_do_hoc_tap`.`binh_luan_BEFORE_INSERT` $$
USE `quan_ly_tien_do_hoc_tap`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quan_ly_tien_do_hoc_tap`.`binh_luan_BEFORE_INSERT` BEFORE INSERT ON `binh_luan` FOR EACH ROW
BEGIN
	/*tìm last id*/
    SET @lastID= (SELECT id FROM binh_luan ORDER BY id DESC LIMIT 1);
    IF @lastID IS NULL OR @lastID = '' THEN
    SET @lastID = 0;
	END IF;
	SET @lastID = @lastID +1;
   	/*check xem có bình luận cha */
    if(NEW.binh_luan_id IS NOT NULL)
    THEN

    /*limit 1 vì chắc chắn sẽ chỉ có 1 bình luận id tương ứng do là primary key*/
    SET @parent_path_enumeration=(SELECT path_enumeration FROM binh_luan WHERE binh_luan.id = New.binh_luan_id LIMIT 1);   
    	/* nếu như không tìm thấy nghĩa là khóa ngoại sai thì sẽ trả về lỗi theo sql*/
    	if(@parent_path_enumeration is not NULL)
    	THEN
        SET NEW.path_enumeration = 
        CONCAT(@parent_path_enumeration,@lastID,'/');
        END IF;
	ELSE
    SET NEW.path_enumeration= CONCAT(@lastID , '/');
	END IF;

END$$


USE `quan_ly_tien_do_hoc_tap`$$
DROP TRIGGER IF EXISTS `quan_ly_tien_do_hoc_tap`.`binh_luan_AFTER_UPDATE` $$
USE `quan_ly_tien_do_hoc_tap`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quan_ly_tien_do_hoc_tap`.`binh_luan_AFTER_UPDATE` AFTER UPDATE ON `binh_luan` FOR EACH ROW
BEGIN
	   	/*không cho cập nhập giá trị */
        
    IF(OLD.binh_luan_id is NULL or  OLD.binh_luan_id != NEW.binh_luan_id)
    THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Không được phép cập nhập cột binh_luan_id';
	END IF;

END$$


USE `quan_ly_tien_do_hoc_tap`$$
DROP TRIGGER IF EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_bat_buoc_AFTER_INSERT` $$
USE `quan_ly_tien_do_hoc_tap`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_bat_buoc_AFTER_INSERT` AFTER INSERT ON `hoc_phan_kkt_bat_buoc` FOR EACH ROW
BEGIN
	/*Kiểm tra xem đã tồn tại hay chưa, nếu khác học kỳ gợi ý thì chỉ có tính 1 lần*/
    if((SELECT COUNT(hoc_phan_kkt_bat_buoc.hoc_phan_id) FROM hoc_phan_kkt_bat_buoc WHERE hoc_phan_kkt_bat_buoc.hoc_phan_id = NEW.hoc_phan_id
       GROUP BY NEW.hoc_phan_id
       )=1
	)
    THEN
    /*chưa tồn tại mới tính số tín chỉ bắt buộc*/
    UPDATE khoi_kien_thuc 
    SET khoi_kien_thuc.tong_tin_chi_ktt_bat_buoc
    = khoi_kien_thuc.tong_tin_chi_ktt_bat_buoc + 
    (SELECT hoc_phan.so_tin_chi FROM hoc_phan WHERE NEW.hoc_phan_id= hoc_phan.id)
    WHERE khoi_kien_thuc.id= NEW.khoi_kien_thuc_id;
    END IF;

END$$


USE `quan_ly_tien_do_hoc_tap`$$
DROP TRIGGER IF EXISTS `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_bat_buoc_AFTER_DELETE` $$
USE `quan_ly_tien_do_hoc_tap`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quan_ly_tien_do_hoc_tap`.`hoc_phan_kkt_bat_buoc_AFTER_DELETE` AFTER DELETE ON `hoc_phan_kkt_bat_buoc` FOR EACH ROW
BEGIN
	/*Kiểm tra xem đã tồn tại hay chưa, nếu có tồn tại nhưng khác học kỳ gợi ý thì không làm gì */
    if( NOT EXISTS(SELECT * FROM hoc_phan_kkt_bat_buoc WHERE hoc_phan_kkt_bat_buoc.hoc_phan_id = OLD.hoc_phan_id))
    THEN
    /*chưa tồn tại mới tính số tín chỉ bắt buộc*/
    UPDATE khoi_kien_thuc 
    SET khoi_kien_thuc.tong_tin_chi_ktt_bat_buoc
    = khoi_kien_thuc.tong_tin_chi_ktt_bat_buoc -
    (SELECT hoc_phan.so_tin_chi FROM hoc_phan WHERE OLD.hoc_phan_id= hoc_phan.id )
    WHERE khoi_kien_thuc.id= OLD.khoi_kien_thuc_id;
    END IF;

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Mar 25, 2023 at 07:18 AM
-- Server version: 8.0.30
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Database: `quan_ly_tien_do_hoc_tap`
--

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint UNSIGNED NOT NULL,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_access_tokens`
--

CREATE TABLE `oauth_access_tokens` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint UNSIGNED DEFAULT NULL,
  `client_id` bigint UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopes` text COLLATE utf8mb4_unicode_ci,
  `revoked` tinyint(1) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_auth_codes`
--

CREATE TABLE `oauth_auth_codes` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint UNSIGNED NOT NULL,
  `client_id` bigint UNSIGNED NOT NULL,
  `scopes` text COLLATE utf8mb4_unicode_ci,
  `revoked` tinyint(1) NOT NULL,
  `expires_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_clients`
--

CREATE TABLE `oauth_clients` (
  `id` bigint UNSIGNED NOT NULL,
  `user_id` bigint UNSIGNED DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `secret` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `redirect` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `personal_access_client` tinyint(1) NOT NULL,
  `password_client` tinyint(1) NOT NULL,
  `revoked` tinyint(1) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_personal_access_clients`
--

CREATE TABLE `oauth_personal_access_clients` (
  `id` bigint UNSIGNED NOT NULL,
  `client_id` bigint UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_refresh_tokens`
--

CREATE TABLE `oauth_refresh_tokens` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `access_token_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `revoked` tinyint(1) NOT NULL,
  `expires_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);


--
-- Indexes for table `oauth_access_tokens`
--
ALTER TABLE `oauth_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD KEY `oauth_access_tokens_user_id_index` (`user_id`);

--
-- Indexes for table `oauth_auth_codes`
--
ALTER TABLE `oauth_auth_codes`
  ADD PRIMARY KEY (`id`),
  ADD KEY `oauth_auth_codes_user_id_index` (`user_id`);

--
-- Indexes for table `oauth_clients`
--
ALTER TABLE `oauth_clients`
  ADD PRIMARY KEY (`id`),
  ADD KEY `oauth_clients_user_id_index` (`user_id`);

--
-- Indexes for table `oauth_personal_access_clients`
--
ALTER TABLE `oauth_personal_access_clients`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `oauth_refresh_tokens`
--
ALTER TABLE `oauth_refresh_tokens`
  ADD PRIMARY KEY (`id`),
  ADD KEY `oauth_refresh_tokens_access_token_id_index` (`access_token_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `oauth_clients`
--
ALTER TABLE `oauth_clients`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `oauth_personal_access_clients`
--
ALTER TABLE `oauth_personal_access_clients`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
COMMIT;

